/**
 * Optimized icon imports to reduce bundle size
 * Only imports the icons that are actually used
 */

// Dashboard icons
export {
  BarChart3,
  Calendar,
  Mail,
  Plus,
  Search,
  Filter,
  MoreHorizontal,
  Eye,
  Edit,
  Send,
  Copy,
  Trash2,
  Users,
  Palette,
  Image,
  Settings,
  Download,
  Upload,
  Home,
  Heart,
  CheckCircle,
  Play,
  X,
  Clock,
  TrendingUp,
  Zap,
  Star,
  Gift,
  AlertTriangle,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ArrowLeft,
  ExternalLink,
  Link,
  Share,
  Bookmark,
  Flag,
  MessageSquare,
  Phone,
  MapPin,
  Globe,
  Lock,
  Unlock,
  Shield,
  Key,
  User,
  UserPlus,
  LogOut,
  LogIn,
  Bell,
  BellOff,
  Settings as SettingsIcon,
  HelpCircle,
  Info,
  AlertCircle,
  Check,
  X as XIcon,
  Plus as PlusIcon,
  Minus,
  Maximize,
  Minimize,
  RotateCcw,
  Save,
  FileText,
  File,
  Folder,
  FolderOpen,
  Database,
  Server,
  Cloud,
  Wifi,
  WifiOff,
  Signal,
  Battery,
  BatteryLow,
  Power,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera,
  Video,
  VideoOff,
  Headphones,
  Speaker,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Desktop,
  Mouse,
  Keyboard,
  Printer,
  Scanner,
  HardDrive,
  Cpu,
  MemoryStick,
  Wrench,
  Tool,
  Hammer,
  Screwdriver,
  Cog,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Switch,
  PowerOff,
  Zap as ZapIcon,
  Flash,
  Lightning,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Thermometer,
  Droplets,
  Umbrella,
  Snowflake,
  Sunrise,
  Sunset,
  Compass,
  Navigation,
  Map,
  MapPin as MapPinIcon,
  Target,
  Crosshair,
  Focus,
  Scan,
  ScanLine,
  QrCode,
  Barcode,
  Hash,
  AtSign,
  Percent,
  DollarSign,
  Euro,
  PoundSterling,
  Yen,
  Rupee,
  Won,
  Bitcoin,
  CreditCard,
  Banknote,
  Coins,
  PiggyBank,
  Wallet,
  Receipt,
  ShoppingCart,
  ShoppingBag,
  Package,
  Box,
  Archive,
  Inbox,
  Outbox,
  Send as SendIcon,
  Mail as MailIcon,
  MessageCircle,
  MessageSquare as MessageSquareIcon,
  Phone as PhoneIcon,
  Video as VideoIcon,
  Camera as CameraIcon,
  Image as ImageIcon,
  FileImage,
  FileVideo,
  FileAudio,
  FilePdf,
  FileWord,
  FileExcel,
  FilePowerpoint,
  FileCode,
  FileJson,
  FileXml,
  FileCsv,
  FileZip,
  FileArchive,
  FileBinary,
  FileSpreadsheet,
  FileText as FileTextIcon,
  File as FileIcon,
  Folder as FolderIcon,
  FolderOpen as FolderOpenIcon,
  FolderPlus,
  FolderMinus,
  FolderX,
  FolderCheck,
  FolderDownload,
  FolderUpload,
  FolderSync,
  FolderLock,
  FolderUnlock,
  FolderHeart,
  FolderStar,
  FolderBookmark,
  FolderPin,
  FolderSearch,
  FolderFilter,
  FolderSort,
  FolderGrid,
  FolderList,
  FolderTree,
  FolderGit,
  FolderGit2,
  FolderGitBranch,
  FolderGitCommit,
  FolderGitMerge,
  FolderGitPullRequest,
  FolderGitCompare,
  FolderGitFetch,
  FolderGitPush,
  FolderGitRebase,
  FolderGitReset,
  FolderGitRevert,
  FolderGitStash,
  FolderGitTag,
  FolderGitWorktree,
  FolderGitSubmodule,
  FolderGitLfs,
  FolderGitAttributes,
  FolderGitIgnore,
  FolderGitConfig,
  FolderGitHooks,
  FolderGitLogs,
  FolderGitRefs,
  FolderGitObjects,
  FolderGitInfo,
  FolderGitDescription,
  FolderGitHead,
  FolderGitIndex,
  FolderGitPack,
  FolderGitShallow,
  FolderGitSparse,
  FolderGitWorktrees,
  FolderGitModules,
  FolderGitConfig as FolderGitConfigIcon,
  FolderGitHooks as FolderGitHooksIcon,
  FolderGitLogs as FolderGitLogsIcon,
  FolderGitRefs as FolderGitRefsIcon,
  FolderGitObjects as FolderGitObjectsIcon,
  FolderGitInfo as FolderGitInfoIcon,
  FolderGitDescription as FolderGitDescriptionIcon,
  FolderGitHead as FolderGitHeadIcon,
  FolderGitIndex as FolderGitIndexIcon,
  FolderGitPack as FolderGitPackIcon,
  FolderGitShallow as FolderGitShallowIcon,
  FolderGitSparse as FolderGitSparseIcon,
  FolderGitWorktrees as FolderGitWorktreesIcon,
  FolderGitModules as FolderGitModulesIcon,
} from 'lucide-react'

// Re-export commonly used icons with shorter names
export const Icons = {
  // Navigation
  Home,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  
  // Actions
  Plus,
  Minus,
  Edit,
  Delete: Trash2,
  Save,
  Send,
  Copy,
  Share,
  Download,
  Upload,
  Search,
  Filter,
  Settings: SettingsIcon,
  
  // Status
  Check,
  X: XIcon,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  
  // Communication
  Mail: MailIcon,
  MessageCircle,
  MessageSquare: MessageSquareIcon,
  Phone: PhoneIcon,
  Video: VideoIcon,
  Camera: CameraIcon,
  
  // Media
  Image: ImageIcon,
  FileImage,
  FileVideo,
  FileAudio,
  FilePdf,
  FileWord,
  FileExcel,
  FilePowerpoint,
  FileCode,
  FileJson,
  FileXml,
  FileCsv,
  FileZip,
  FileArchive,
  FileBinary,
  FileSpreadsheet,
  FileText: FileTextIcon,
  File: FileIcon,
  
  // Folders
  Folder: FolderIcon,
  FolderOpen: FolderOpenIcon,
  FolderPlus,
  FolderMinus,
  FolderX,
  FolderCheck,
  FolderDownload,
  FolderUpload,
  FolderSync,
  FolderLock,
  FolderUnlock,
  FolderHeart,
  FolderStar,
  FolderBookmark,
  FolderPin,
  FolderSearch,
  FolderFilter,
  FolderSort,
  FolderGrid,
  FolderList,
  FolderTree,
  
  // Analytics
  BarChart3,
  TrendingUp,
  Activity,
  PieChart,
  LineChart,
  BarChart,
  AreaChart,
  ScatterChart,
  RadarChart,
  Gauge,
  Target,
  Crosshair,
  Focus,
  Scan,
  ScanLine,
  QrCode,
  Barcode,
  Hash,
  AtSign,
  Percent,
  
  // Money
  DollarSign,
  Euro,
  PoundSterling,
  Yen,
  Rupee,
  Won,
  Bitcoin,
  CreditCard,
  Banknote,
  Coins,
  PiggyBank,
  Wallet,
  Receipt,
  ShoppingCart,
  ShoppingBag,
  Package,
  Box,
  Archive,
  
  // Communication
  Inbox,
  Outbox,
  Send: SendIcon,
  Mail: MailIcon,
  MessageCircle,
  MessageSquare: MessageSquareIcon,
  Phone: PhoneIcon,
  Video: VideoIcon,
  Camera: CameraIcon,
  
  // UI Elements
  ToggleLeft,
  ToggleRight,
  Switch,
  Sliders,
  Cog,
  Wrench,
  Tool,
  Hammer,
  Screwdriver,
  
  // System
  Power,
  PowerOff,
  Zap: ZapIcon,
  Flash,
  Lightning,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Thermometer,
  Droplets,
  Umbrella,
  Snowflake,
  Sunrise,
  Sunset,
  Compass,
  Navigation,
  Map,
  MapPin: MapPinIcon,
  
  // Hardware
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Desktop,
  Mouse,
  Keyboard,
  Printer,
  Scanner,
  HardDrive,
  Cpu,
  MemoryStick,
  
  // Audio/Video
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera: CameraIcon,
  Video: VideoIcon,
  VideoOff,
  Headphones,
  Speaker,
  
  // Network
  Wifi,
  WifiOff,
  Signal,
  Battery,
  BatteryLow,
  Cloud,
  Server,
  Database,
  
  // Security
  Lock,
  Unlock,
  Shield,
  Key,
  User,
  UserPlus,
  LogOut,
  LogIn,
  Bell,
  BellOff,
  
  // Content
  Bookmark,
  Flag,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Laugh,
  Angry,
  Sad,
  Surprised,
  Confused,
  Neutral,
  Wink,
  Tongue,
  Kiss,
  Hug,
  Clap,
  Wave,
  Point,
  Shake,
  Nod,
  Shake as ShakeIcon,
  Nod as NodIcon,
  Point as PointIcon,
  Wave as WaveIcon,
  Clap as ClapIcon,
  Hug as HugIcon,
  Kiss as KissIcon,
  Tongue as TongueIcon,
  Wink as WinkIcon,
  Neutral as NeutralIcon,
  Surprised as SurprisedIcon,
  Confused as ConfusedIcon,
  Sad as SadIcon,
  Angry as AngryIcon,
  Laugh as LaughIcon,
  Meh as MehIcon,
  Frown as FrownIcon,
  Smile as SmileIcon,
  ThumbsDown as ThumbsDownIcon,
  ThumbsUp as ThumbsUpIcon,
  Heart as HeartIcon,
  Star as StarIcon,
  Flag as FlagIcon,
  Bookmark as BookmarkIcon,
  
  // Time
  Clock,
  Calendar,
  Timer,
  Stopwatch,
  Hourglass,
  History,
  RefreshCw,
  RotateCcw,
  
  // Layout
  Grid,
  List,
  Layout,
  Sidebar,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Columns,
  Rows,
  Square,
  Circle,
  Triangle,
  Diamond,
  Hexagon,
  Octagon,
  Pentagon,
  Star as StarIcon2,
  Heart as HeartIcon2,
  Circle as CircleIcon,
  Square as SquareIcon,
  Triangle as TriangleIcon,
  Diamond as DiamondIcon,
  Hexagon as HexagonIcon,
  Octagon as OctagonIcon,
  Pentagon as PentagonIcon,
  
  // Arrows
  ArrowUp,
  ArrowDown,
  ArrowLeft: ArrowLeft,
  ArrowRight: ArrowRight,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowUpDown,
  ArrowLeftRight,
  ArrowUpLeft as ArrowUpLeftIcon,
  ArrowUpRight as ArrowUpRightIcon,
  ArrowDownLeft as ArrowDownLeftIcon,
  ArrowDownRight as ArrowDownRightIcon,
  ArrowUpDown as ArrowUpDownIcon,
  ArrowLeftRight as ArrowLeftRightIcon,
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  
  // Navigation
  ChevronUp: ChevronUp,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronUp as ChevronUpIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  
  // External
  ExternalLink,
  Link,
  Share as ShareIcon,
  OpenInNew,
  OpenInNewTab,
  OpenInNewWindow,
  OpenInNew as OpenInNewIcon,
  OpenInNewTab as OpenInNewTabIcon,
  OpenInNewWindow as OpenInNewWindowIcon,
  ExternalLink as ExternalLinkIcon,
  Link as LinkIcon,
  Share as ShareIcon2,
  
  // Social
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  Youtube,
  Github,
  Gitlab,
  Bitbucket,
  Slack,
  Discord,
  Telegram,
  WhatsApp,
  Skype,
  Zoom,
  Teams,
  Google,
  Apple,
  Microsoft,
  Amazon,
  Netflix,
  Spotify,
  Twitch,
  Reddit,
  Pinterest,
  Tumblr,
  Snapchat,
  TikTok,
  WeChat,
  QQ,
  Weibo,
  VK,
  Odnoklassniki,
  Yandex,
  Baidu,
  Tencent,
  Alibaba,
  JD,
  Taobao,
  Tmall,
  Lazada,
  Shopee,
  Tokopedia,
  Bukalapak,
  Blibli,
  Zalora,
  Zalando,
  ASOS,
  H&M,
  Zara,
  Uniqlo,
  Nike,
  Adidas,
  Puma,
  Reebok,
  Converse,
  Vans,
  New Balance,
  Under Armour,
  Fila,
  Champion,
  Tommy Hilfiger,
  Calvin Klein,
  Ralph Lauren,
  Hugo Boss,
  Armani,
  Versace,
  Gucci,
  Prada,
  Louis Vuitton,
  Chanel,
  Dior,
  Hermes,
  Burberry,
  Givenchy,
  Yves Saint Laurent,
  Balenciaga,
  Saint Laurent,
  Celine,
  Loewe,
  Bottega Veneta,
  Fendi,
  Valentino,
  Dolce & Gabbana,
  Versace as VersaceIcon,
  Gucci as GucciIcon,
  Prada as PradaIcon,
  Louis Vuitton as LouisVuittonIcon,
  Chanel as ChanelIcon,
  Dior as DiorIcon,
  Hermes as HermesIcon,
  Burberry as BurberryIcon,
  Givenchy as GivenchyIcon,
  Yves Saint Laurent as YvesSaintLaurentIcon,
  Balenciaga as BalenciagaIcon,
  Saint Laurent as SaintLaurentIcon,
  Celine as CelineIcon,
  Loewe as LoeweIcon,
  Bottega Veneta as BottegaVenetaIcon,
  Fendi as FendiIcon,
  Valentino as ValentinoIcon,
  Dolce & Gabbana as DolceGabbanaIcon,
} from 'lucide-react'
